"""Update participant table schema

Revision ID: 6c8bff60589e
Revises: 94cd3eaffb76
Create Date: 2024-06-30 01:14:26.875651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8bff60589e'
down_revision = '94cd3eaffb76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_user')
    # ### end Alembic commands ###
